#!/bin/bash
# PDFChat Test Commands - Quick Reference
# Copy and paste these commands to run various test scenarios

echo "=== PDFChat Test Commands ==="
echo ""
echo "BASIC COMMANDS:"
echo "  pytest                          # Run all tests"
echo "  pytest -v                       # Run all tests (verbose)"
echo "  pytest --tb=short               # Run all tests (short traceback)"
echo ""
echo "COVERAGE COMMANDS:"
echo "  pytest --cov=.                  # Run tests with coverage"
echo "  pytest --cov=. --cov-report=html  # Generate HTML coverage report"
echo "  pytest --cov=. --cov-report=term-missing  # Terminal coverage report"
echo ""
echo "RUN SPECIFIC TESTS:"
echo "  pytest tests/unit/              # Run all unit tests"
echo "  pytest tests/integration/       # Run all integration tests"
echo "  pytest tests/unit/test_auth_service.py  # Run specific file"
echo "  pytest tests/unit/test_auth_service.py::TestAuthServicePasswordHashing  # Run class"
echo "  pytest tests/unit/test_auth_service.py::TestAuthServicePasswordHashing::test_hash_password  # Run test"
echo ""
echo "DEBUG COMMANDS:"
echo "  pytest -s                       # Show print statements"
echo "  pytest -x                       # Stop on first failure"
echo "  pytest --pdb                    # Drop into debugger on failure"
echo "  pytest -vv                      # Very verbose output"
echo "  pytest -l                       # Show local variables on failure"
echo ""
echo "SEARCH/FILTER COMMANDS:"
echo "  pytest -k \"auth\"                # Run tests matching pattern"
echo "  pytest -k \"test_create\"         # Run all create tests"
echo "  pytest -k \"not slow\"            # Run all tests except slow ones"
echo ""
echo "OTHER USEFUL COMMANDS:"
echo "  pytest --collect-only           # Show all tests without running"
echo "  pytest --collect-only -q        # Show all tests (quiet)"
echo "  pytest --lf                     # Run last failed tests"
echo "  pytest --ff                     # Run failed tests first"
echo "  pytest -x --lf                  # Stop on first failure, last failed"
echo ""
echo "CI/CD COMMANDS:"
echo "  pytest --cov=. --cov-report=xml  # Generate XML report (for CI)"
echo "  pytest --junitxml=report.xml     # Generate JUnit XML report"
echo "  pytest -m unit                   # Run only unit tests (if marked)"
echo ""
